// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugxlsewsbuxkwtvsclfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVneGxzZXdzYnV4a3d0dnNjbGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjU4MTUsImV4cCI6MjA3MzUwMTgxNX0.vZP25uUe9uAUWakV2HSUT5R25tG2PVhbRJ5R-1ogOos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});